import numpy as np
from Mueller import Mueller

def RotatingWPPolSops(rot, philamina):
    """
    Generates SOPs matrix A and computes its condition number.

    Parameters
    ----------
    rot : array-like
        Rotation angles (radians)
    philamina : float
        Retardance of the waveplate (radians)

    Returns
    -------
    CN : float
        Condition number of matrix A
    A : np.ndarray (Nrot x 4)
        Stokes vectors generated by the system
    """

    Sini = np.array([1, 1, 0, 0])

    rot = np.array(rot)
    Nrot = len(rot)

    A = np.zeros((Nrot, 4))

    for k in range(Nrot):
        M = Mueller('waveplate', rot[k], philamina)
        A[k, :] = M @ Sini

    CN = np.linalg.cond(A)

    return CN, A
# CN  = (CN - sqrt(3))*1.e6;